#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_ROOT="$(cd "$APP_ROOT/.." && pwd)"
DEFAULT_NODE_BIN="$WORKSPACE_ROOT/.runtime/node-v22.23.1-linux-x64/bin/node"
NODE_BIN="${NODE_BIN:-$DEFAULT_NODE_BIN}"

if [[ ! -x "$NODE_BIN" ]]; then
  for candidate in \
    "$HOME/.local/node-v24.15.0-linux-x64/bin/node" \
    "$APP_ROOT/.runtime/node-v22.23.1-linux-x64/bin/node" \
    "/usr/local/bin/node" \
    "$(command -v node 2>/dev/null || true)"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      NODE_BIN="$candidate"
      break
    fi
  done
fi

if [[ ! -x "$NODE_BIN" ]]; then
  echo "Node runtime not found. Set NODE_BIN or install node." >&2
  exit 127
fi

LOG_DIR="${CASSA_RUNTIME_LOG_DIR:-$APP_ROOT/logs}"
mkdir -p "$LOG_DIR"

BACKEND_PID="$LOG_DIR/backend-linux-current.pid"
REALTIME_PID="$LOG_DIR/backend-realtime-current.pid"
API_WORKER_PID="$LOG_DIR/backend-api-worker-current.pid"
FRONTEND_PID="$LOG_DIR/frontends-linux-current.pid"
BACKEND_OUT="$LOG_DIR/backend-linux-current.out.log"
BACKEND_ERR="$LOG_DIR/backend-linux-current.err.log"
REALTIME_OUT="$LOG_DIR/backend-realtime-current.out.log"
REALTIME_ERR="$LOG_DIR/backend-realtime-current.err.log"
API_WORKER_OUT="$LOG_DIR/backend-api-worker-current.out.log"
API_WORKER_ERR="$LOG_DIR/backend-api-worker-current.err.log"
FRONTEND_OUT="$LOG_DIR/frontends-linux-current.out.log"
FRONTEND_ERR="$LOG_DIR/frontends-linux-current.err.log"
BACKEND_PORT="${BACKEND_PORT:-5381}"
FRONTEND_PORT="${FRONTEND_PORT:-5380}"
REALTIME_GATEWAY_ENABLED="${BACKEND_REALTIME_GATEWAY_ENABLED:-0}"
REALTIME_PORT="${BACKEND_REALTIME_PORT:-5382}"
API_WORKER_ENABLED="${BACKEND_API_WORKER_ENABLED:-0}"
API_WORKER_PORT="${BACKEND_API_WORKER_PORT:-5383}"
API_WORKER_COUNT="${BACKEND_API_WORKER_COUNT:-1}"
if ! [[ "$API_WORKER_COUNT" =~ ^[0-9]+$ ]]; then
  API_WORKER_COUNT=1
fi
if (( API_WORKER_COUNT < 1 )); then
  API_WORKER_COUNT=1
elif (( API_WORKER_COUNT > 8 )); then
  API_WORKER_COUNT=8
fi
API_WORKER_PORT_LIST=()
if [[ -n "${BACKEND_API_WORKER_PORTS:-}" ]]; then
  IFS=',' read -r -a configured_api_worker_ports <<<"${BACKEND_API_WORKER_PORTS:-}"
  for configured_port in "${configured_api_worker_ports[@]}"; do
    configured_port="$(xargs <<<"$configured_port")"
    if [[ "$configured_port" =~ ^[0-9]+$ ]]; then
      API_WORKER_PORT_LIST+=("$configured_port")
    fi
  done
  if (( ${#API_WORKER_PORT_LIST[@]} == 0 )); then
    API_WORKER_PORT_LIST=("$API_WORKER_PORT")
  fi
  API_WORKER_COUNT="${#API_WORKER_PORT_LIST[@]}"
else
  for worker_index in $(seq 0 $((API_WORKER_COUNT - 1))); do
    API_WORKER_PORT_LIST+=("$((API_WORKER_PORT + worker_index))")
  done
fi
OWNER_PROCESS_ROLE="${BACKEND_PROCESS_ROLE:-monolith}"
RELATIONAL_ENABLED="${BACKEND_RELATIONAL_ENABLED:-0}"
RELATIONAL_MODE="${BACKEND_RELATIONAL_MODE:-off}"
RELATIONAL_SHADOW_SYNC_ENABLED="${BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED:-1}"
EVENT_OUTBOX_FLAG="${EVENT_OUTBOX_ENABLED:-0}"
MYSQL_APP_STATE_DOMAINS_FLAG="${BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS:-1}"
ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE="${BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_COMP_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CANARY:-0}"
ORDER_CREATE_SYNC_CANCEL_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_CANARY:-0}"
ORDER_CREATE_SYNC_CANARY="${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANARY:-0}"
ORDER_SYNC_CANARY="${BACKEND_MULTI_PROCESS_ORDER_SYNC_CANARY:-0}"
if [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_COMP_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANCEL_CANARY" == "1" || "$ORDER_CREATE_SYNC_CANARY" == "1" || "$ORDER_SYNC_CANARY" == "1" ]]; then
  export BACKEND_REALTIME_GATEWAY_ENABLED="${BACKEND_REALTIME_GATEWAY_ENABLED:-1}"
  export BACKEND_API_WORKER_ENABLED="${BACKEND_API_WORKER_ENABLED:-1}"
  export BACKEND_PROCESS_ROLE="${BACKEND_PROCESS_ROLE:-api-owner}"
  export BACKEND_RELATIONAL_ENABLED="${BACKEND_RELATIONAL_ENABLED:-1}"
  export BACKEND_RELATIONAL_MODE="${BACKEND_RELATIONAL_MODE:-shadow}"
  export BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED="${BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED:-0}"
  export EVENT_OUTBOX_ENABLED="${EVENT_OUTBOX_ENABLED:-1}"
  export BACKEND_MULTI_PROCESS_READ_WORKERS="${BACKEND_MULTI_PROCESS_READ_WORKERS:-1}"
  export BACKEND_MULTI_PROCESS_READ_STATE_EXTERNALIZED="${BACKEND_MULTI_PROCESS_READ_STATE_EXTERNALIZED:-1}"
  export BACKEND_MULTI_PROCESS_ORDER_WORKERS="${BACKEND_MULTI_PROCESS_ORDER_WORKERS:-1}"
  export BACKEND_MULTI_PROCESS_ORDER_STATE_EXTERNALIZED="${BACKEND_MULTI_PROCESS_ORDER_STATE_EXTERNALIZED:-1}"
  export BACKEND_APP_STATE_SPLIT_TABLE_STATES="${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-externalized}"
  export BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS="${BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS:-1}"
  export BACKEND_RELATIONAL_ORDERS_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_CREATE_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_CREATE_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_SYNC_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_SYNC_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_CANCEL_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_CANCEL_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_COMP_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_COMP_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_STORNO_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_STORNO_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_CORRECT_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_CORRECT_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_BAR_REPLACEMENT_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_BAR_REPLACEMENT_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_LINE_SPLIT_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_LINE_SPLIT_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_PRICE_OVERRIDE_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_PRICE_OVERRIDE_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_TRANSFER_REQUEST_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_TRANSFER_REQUEST_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_TRANSFER_RESOLVE_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_TRANSFER_RESOLVE_WRITE_PRIMARY:-1}"
  export BACKEND_RELATIONAL_ORDERS_TRANSFER_FORCE_WRITE_PRIMARY="${BACKEND_RELATIONAL_ORDERS_TRANSFER_FORCE_WRITE_PRIMARY:-1}"
  export BACKEND_ORDERS_ASYNC_APPSTATE_FLUSH="${BACKEND_ORDERS_ASYNC_APPSTATE_FLUSH:-1}"
  export BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO="${BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO:-1}"
  if [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split,POST /api/integration/orders/transfer/resolve,POST /api/integration/orders/transfer/request,POST /api/integration/orders/line/price-override,POST /api/integration/orders/transfer/force,POST /api/integration/orders/storno}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split,POST /api/integration/orders/transfer/resolve,POST /api/integration/orders/transfer/request,POST /api/integration/orders/line/price-override,POST /api/integration/orders/transfer/force}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split,POST /api/integration/orders/transfer/resolve,POST /api/integration/orders/transfer/request,POST /api/integration/orders/line/price-override}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split,POST /api/integration/orders/transfer/resolve,POST /api/integration/orders/transfer/request}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split,POST /api/integration/orders/transfer/resolve}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge,POST /api/integration/orders/line/split}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct,POST /api/integration/orders/replacement/bar-charge,POST /api/orders/replacement/bar-charge}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp,POST /api/integration/orders/correct}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_COMP_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel,POST /api/integration/orders/comp}"
  elif [[ "$ORDER_CREATE_SYNC_CANCEL_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync,POST /api/integration/orders/cancel}"
  elif [[ "$ORDER_CREATE_SYNC_CANARY" == "1" ]]; then
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/create,POST /api/integration/orders/sync}"
  else
    export BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-POST /api/integration/orders/sync}"
  fi

  REALTIME_GATEWAY_ENABLED="$BACKEND_REALTIME_GATEWAY_ENABLED"
  API_WORKER_ENABLED="$BACKEND_API_WORKER_ENABLED"
  OWNER_PROCESS_ROLE="$BACKEND_PROCESS_ROLE"
  RELATIONAL_ENABLED="$BACKEND_RELATIONAL_ENABLED"
  RELATIONAL_MODE="$BACKEND_RELATIONAL_MODE"
  RELATIONAL_SHADOW_SYNC_ENABLED="$BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED"
  EVENT_OUTBOX_FLAG="$EVENT_OUTBOX_ENABLED"
  MYSQL_APP_STATE_DOMAINS_FLAG="$BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS"
  ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE="$BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO"
fi
if [[ "$REALTIME_GATEWAY_ENABLED" == "1" && -z "${BACKEND_PROCESS_ROLE:-}" ]]; then
  OWNER_PROCESS_ROLE="api-owner"
fi
if [[ "$REALTIME_GATEWAY_ENABLED" == "1" ]]; then
  RELATIONAL_ENABLED="${BACKEND_RELATIONAL_ENABLED:-1}"
  RELATIONAL_MODE="${BACKEND_RELATIONAL_MODE:-shadow}"
  RELATIONAL_SHADOW_SYNC_ENABLED="${BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED:-0}"
  EVENT_OUTBOX_FLAG="${EVENT_OUTBOX_ENABLED:-1}"
fi
FRONTEND_REALTIME_ORIGIN="${BACKEND_REALTIME_ORIGIN:-}"
if [[ "$REALTIME_GATEWAY_ENABLED" == "1" && -z "$FRONTEND_REALTIME_ORIGIN" ]]; then
  FRONTEND_REALTIME_ORIGIN="http://127.0.0.1:${REALTIME_PORT}"
fi
FRONTEND_API_WORKER_ORIGIN="${BACKEND_API_WORKER_ORIGIN:-}"
if [[ "$API_WORKER_ENABLED" == "1" && -z "$FRONTEND_API_WORKER_ORIGIN" ]]; then
  FRONTEND_API_WORKER_ORIGIN=""
  for worker_port in "${API_WORKER_PORT_LIST[@]}"; do
    if [[ -n "$FRONTEND_API_WORKER_ORIGIN" ]]; then
      FRONTEND_API_WORKER_ORIGIN+=","
    fi
    FRONTEND_API_WORKER_ORIGIN+="http://127.0.0.1:${worker_port}"
  done
fi

is_managed_process() {
  local pid="$1"
  local process_cwd process_exe expected_exe
  [[ "$pid" =~ ^[0-9]+$ ]] || return 1
  process_cwd="$(readlink -e "/proc/$pid/cwd" 2>/dev/null || true)"
  process_exe="$(readlink -e "/proc/$pid/exe" 2>/dev/null || true)"
  expected_exe="$(readlink -e "$NODE_BIN" 2>/dev/null || true)"
  [[ -n "$process_cwd" && -n "$process_exe" && -n "$expected_exe" ]] &&
    [[ "$process_cwd" == "$APP_ROOT" || "$process_cwd" == "$APP_ROOT/"* ]] &&
    [[ "$process_exe" == "$expected_exe" ]]
}

stop_pid_file() {
  local pid_file="$1"
  if [[ ! -f "$pid_file" ]]; then
    return 0
  fi
  local pid start_identity current_identity
  pid="$(cat "$pid_file" 2>/dev/null || true)"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    if ! is_managed_process "$pid"; then
      echo "Ignoring stale or foreign pid $pid from $pid_file" >&2
      rm -f "$pid_file"
      return 0
    fi
    start_identity="$(awk '{ print $22 }' "/proc/$pid/stat" 2>/dev/null || true)"
    echo "Stopping pid $pid from $pid_file"
    kill "$pid" 2>/dev/null || true
    sleep 1
    if kill -0 "$pid" 2>/dev/null; then
      current_identity="$(awk '{ print $22 }' "/proc/$pid/stat" 2>/dev/null || true)"
      if [[ -n "$start_identity" && "$current_identity" == "$start_identity" ]] &&
         is_managed_process "$pid"; then
        kill -9 "$pid" 2>/dev/null || true
      fi
    fi
  fi
  rm -f "$pid_file"
}

stop_port() {
  local port="$1"
  if ss -ltnH "sport = :$port" 2>/dev/null | grep -q .; then
    echo "Porta gia occupata, avvio annullato: $port" >&2
    exit 1
  fi
}

wait_http() {
  local url="$1"
  local label="$2"
  local curl_args=(-fsS --max-time 3)
  if [[ "$url" == https://* ]]; then
    curl_args=(-k -fsS --max-time 3)
  fi
  for _ in $(seq 1 60); do
    if curl "${curl_args[@]}" "$url" >/dev/null 2>&1; then
      echo "$label OK: $url"
      return 0
    fi
    sleep 1
  done
  echo "$label FAILED: $url" >&2
  return 1
}

select_lan_ip() {
  local candidate
  if [[ -n "${FRONTEND_LAN_IP:-}" ]] &&
     [[ -f "$APP_ROOT/mobile-frontend/certs/${FRONTEND_LAN_IP}.pem" ]] &&
     [[ -f "$APP_ROOT/mobile-frontend/certs/${FRONTEND_LAN_IP}-key.pem" ]]; then
    echo "$FRONTEND_LAN_IP"
    return 0
  fi
  for candidate in $(hostname -I 2>/dev/null || true); do
    if [[ -f "$APP_ROOT/mobile-frontend/certs/${candidate}.pem" ]] &&
       [[ -f "$APP_ROOT/mobile-frontend/certs/${candidate}-key.pem" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  echo "192.168.0.28"
}

resolve_order_workflow_audit_go() {
  ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE="${BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO:-0}"
  if [[ "$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE" != "1" ]]; then
    return 0
  fi

  local audit_output
  local audit_args=(
    "cassa-frontend/scripts/order-workflow-externalization-audit.mjs"
    "--json-only"
    "--no-write"
  )
  if [[ -n "${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" ]]; then
    audit_args+=("--route-allowlist" "${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}")
  fi
  if [[ "${BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD:-0}" == "1" ]]; then
    audit_args+=("--allow-wildcard")
  fi
  if ! audit_output="$(cd "$APP_ROOT" && "$NODE_BIN" "${audit_args[@]}" 2>/dev/null)"; then
    echo "WARNING: order workflow audit check failed; forcing BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO=0 for this restart." >&2
    ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE=0
    return 0
  fi

  if [[ -n "${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" ]]; then
    if printf '%s' "$audit_output" | "$NODE_BIN" -e 'const fs = require("node:fs"); const payload = JSON.parse(fs.readFileSync(0, "utf8")); process.exit(payload.orderWorkerAllowlistAudit?.goNoGo === "go" ? 0 : 1);'; then
      return 0
    fi
    echo "WARNING: order worker route allowlist audit is not GO; forcing BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO=0 for this restart." >&2
    echo "WARNING: current audit summary: $(tr '\n' ' ' <<<"$audit_output" | sed -E 's/[[:space:]]+/ /g' | cut -c1-220)" >&2
    ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE=0
    return 0
  fi

  if ! grep -q '"orderWorkersGoNoGo"[[:space:]]*:[[:space:]]*"go"' <<<"$audit_output"; then
    echo "WARNING: order workflow audit is not GO; forcing BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO=0 for this restart." >&2
    echo "WARNING: current audit summary: $(tr '\n' ' ' <<<"$audit_output" | sed -E 's/[[:space:]]+/ /g' | cut -c1-220)" >&2
    ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE=0
  fi
}

print_order_worker_prerequisites() {
  local requested=0
  local missing=0
  local name
  local prerequisites=(
    "BACKEND_MULTI_PROCESS_ORDER_WORKERS"
    "BACKEND_MULTI_PROCESS_ORDER_STATE_EXTERNALIZED"
    "BACKEND_APP_STATE_SPLIT_TABLE_STATES"
    "BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS"
    "BACKEND_RELATIONAL_ORDERS_WRITE_PRIMARY"
    "BACKEND_ORDERS_ASYNC_APPSTATE_FLUSH"
    "EVENT_OUTBOX_ENABLED"
    "BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO"
    "BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST"
  )
  if [[ "${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" == *"*"* ]]; then
    prerequisites+=("BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD")
  fi
  for name in "${prerequisites[@]}"; do
    local value="${!name:-0}"
    if [[ "$name" == "BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO" ]]; then
      value="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE"
    elif [[ "$name" == "BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS" ]]; then
      value="$MYSQL_APP_STATE_DOMAINS_FLAG"
    elif [[ "$name" == "EVENT_OUTBOX_ENABLED" ]]; then
      value="$EVENT_OUTBOX_FLAG"
    fi
    if [[ "$name" == "BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST" && -n "${!name:-}" ]]; then
      requested=1
    elif [[ "$name" == "BACKEND_APP_STATE_SPLIT_TABLE_STATES" && "$value" == "externalized" ]]; then
      requested=1
    elif [[ "$value" == "1" ]]; then
      requested=1
    fi
  done
  if [[ "$requested" != "1" ]]; then
    echo "Order workers: disabled (default safe owner routing)"
    return 0
  fi

  echo "Order worker prerequisites:"
  for name in "${prerequisites[@]}"; do
    local value="${!name:-0}"
    if [[ "$name" == "BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO" ]]; then
      value="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE"
    elif [[ "$name" == "BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS" ]]; then
      value="$MYSQL_APP_STATE_DOMAINS_FLAG"
    elif [[ "$name" == "EVENT_OUTBOX_ENABLED" ]]; then
      value="$EVENT_OUTBOX_FLAG"
    fi
    if [[ "$name" == "BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST" && -n "${!name:-}" ]]; then
      echo "- OK $name=${!name}"
    elif [[ "$name" == "BACKEND_APP_STATE_SPLIT_TABLE_STATES" && "$value" == "externalized" ]]; then
      echo "- OK $name=externalized"
    elif [[ "$value" == "1" ]]; then
      echo "- OK $name"
    else
      echo "- MISSING $name"
      missing=1
    fi
  done
  if [[ "$missing" == "1" ]]; then
    echo "WARNING: order workers requested partially; order mutations will stay routed to owner." >&2
    echo "WARNING: run cassa-frontend/scripts/order-workflow-externalization-audit.mjs and report:process-topology before enabling order workers." >&2
  else
    echo "Order workers: prerequisites complete; route guard may allow order-workflow on api-worker."
  fi
}

echo "Restarting Sistema Cassa backend/frontend"
echo "App root: $APP_ROOT"
echo "Node: $NODE_BIN"
resolve_order_workflow_audit_go
print_order_worker_prerequisites
if [[ "${BACKEND_RESTART_DRY_RUN:-0}" == "1" ]]; then
  echo "Dry run enabled: no process will be stopped or started."
  echo "Effective topology:"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_STORNO_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_TRANSFER_FORCE_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_PRICE_OVERRIDE_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_TRANSFER_REQUEST_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_TRANSFER_RESOLVE_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_LINE_SPLIT_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_BAR_REPLACEMENT_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CORRECT_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_COMP_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANCEL_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANARY=${BACKEND_MULTI_PROCESS_ORDER_CREATE_SYNC_CANARY:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_SYNC_CANARY=${BACKEND_MULTI_PROCESS_ORDER_SYNC_CANARY:-0}"
  echo "- BACKEND_PROCESS_ROLE=$OWNER_PROCESS_ROLE"
  echo "- BACKEND_REALTIME_GATEWAY_ENABLED=$REALTIME_GATEWAY_ENABLED"
  echo "- BACKEND_API_WORKER_ENABLED=$API_WORKER_ENABLED"
  echo "- BACKEND_API_WORKER_COUNT=$API_WORKER_COUNT"
  echo "- BACKEND_API_WORKER_PORTS=$(IFS=,; echo "${API_WORKER_PORT_LIST[*]}")"
  echo "- BACKEND_RELATIONAL_ENABLED=$RELATIONAL_ENABLED"
  echo "- BACKEND_RELATIONAL_MODE=$RELATIONAL_MODE"
  echo "- BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED=$RELATIONAL_SHADOW_SYNC_ENABLED"
  echo "- EVENT_OUTBOX_ENABLED=$EVENT_OUTBOX_FLAG"
  echo "- BACKEND_APP_STATE_SPLIT_TABLE_STATES=${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-off}"
  echo "- BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS=$MYSQL_APP_STATE_DOMAINS_FLAG"
  echo "- BACKEND_RELATIONAL_ORDERS_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_CREATE_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_CREATE_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_SYNC_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_SYNC_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_CANCEL_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_CANCEL_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_COMP_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_COMP_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_STORNO_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_STORNO_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_CORRECT_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_CORRECT_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_BAR_REPLACEMENT_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_BAR_REPLACEMENT_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_LINE_SPLIT_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_LINE_SPLIT_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_PRICE_OVERRIDE_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_PRICE_OVERRIDE_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_TRANSFER_REQUEST_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_TRANSFER_REQUEST_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_TRANSFER_RESOLVE_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_TRANSFER_RESOLVE_WRITE_PRIMARY:-0}"
  echo "- BACKEND_RELATIONAL_ORDERS_TRANSFER_FORCE_WRITE_PRIMARY=${BACKEND_RELATIONAL_ORDERS_TRANSFER_FORCE_WRITE_PRIMARY:-0}"
  echo "- BACKEND_ORDERS_ASYNC_APPSTATE_FLUSH=${BACKEND_ORDERS_ASYNC_APPSTATE_FLUSH:-0}"
  echo "- BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO=$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE"
  echo "- BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST=${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}"
  exit 0
fi

require_runtime_setting() {
  local setting_name="$1"
  local component_name="$2"
  if [[ -z "${!setting_name:-}" ]]; then
    echo "Missing required $component_name setting: $setting_name" >&2
    exit 1
  fi
}

if [[ "${BACKEND_DB_MODE:-mysql}" == "mysql" ]]; then
  for setting_name in \
    BACKEND_MYSQL_HOST \
    BACKEND_MYSQL_PORT \
    BACKEND_MYSQL_USER \
    BACKEND_MYSQL_PASSWORD \
    BACKEND_MYSQL_DATABASE; do
    require_runtime_setting "$setting_name" "MySQL"
  done
fi

if [[ "${AUTOMATIC_CASH_GATEWAY_ENABLED:-1}" == "1" ]]; then
  for setting_name in \
    AUTOMATIC_CASH_GATEWAY_BASE_URL \
    AUTOMATIC_CASH_GATEWAY_USERNAME \
    AUTOMATIC_CASH_GATEWAY_PASSWORD; do
    require_runtime_setting "$setting_name" "automatic cash gateway"
  done
fi

stop_pid_file "$BACKEND_PID"
stop_pid_file "$REALTIME_PID"
stop_pid_file "$API_WORKER_PID"
for worker_port in "${API_WORKER_PORT_LIST[@]}"; do
  stop_pid_file "$LOG_DIR/backend-api-worker-${worker_port}.pid"
done
stop_pid_file "$FRONTEND_PID"
stop_port "$BACKEND_PORT"
stop_port "$REALTIME_PORT"
for worker_port in "${API_WORKER_PORT_LIST[@]}"; do
  stop_port "$worker_port"
done
stop_port "$FRONTEND_PORT"

LAN_IP="$(select_lan_ip)"
CERT_PATH="$APP_ROOT/mobile-frontend/certs/${LAN_IP}.pem"
KEY_PATH="$APP_ROOT/mobile-frontend/certs/${LAN_IP}-key.pem"

if [[ ! -f "$CERT_PATH" || ! -f "$KEY_PATH" ]]; then
  echo "Missing HTTPS cert/key for $LAN_IP:" >&2
  echo "- $CERT_PATH" >&2
  echo "- $KEY_PATH" >&2
  exit 1
fi

(
  cd "$APP_ROOT/cassa-frontend"
  nohup setsid env \
    NODE_ENV=development \
    BACKEND_PROCESS_ROLE="$OWNER_PROCESS_ROLE" \
    APP_STATE_DIRTY_TRACKING="${APP_STATE_DIRTY_TRACKING:-1}" \
    SCOPED_READS="${SCOPED_READS:-1}" \
    SSE_EVENT_PAYLOAD="${SSE_EVENT_PAYLOAD:-1}" \
	    RUNTIME_METRICS="${RUNTIME_METRICS:-1}" \
	    RUNTIME_METRICS_QUEUE_SAMPLE_LIMIT="${RUNTIME_METRICS_QUEUE_SAMPLE_LIMIT:-1200}" \
	    LANE_PAYMENTS="${LANE_PAYMENTS:-1}" \
	    PAYMENT_LANE_CONCURRENCY="${PAYMENT_LANE_CONCURRENCY:-2}" \
	    LANE_ROOMS="${LANE_ROOMS:-1}" \
		    ROOM_LANE_CONCURRENCY="${ROOM_LANE_CONCURRENCY:-2}" \
		    LANE_RESERVATIONS="${LANE_RESERVATIONS:-1}" \
		    RESERVATION_LANE_CONCURRENCY="${RESERVATION_LANE_CONCURRENCY:-1}" \
		    LANE_NOTIFICATIONS="${LANE_NOTIFICATIONS:-1}" \
		    NOTIFICATION_LANE_CONCURRENCY="${NOTIFICATION_LANE_CONCURRENCY:-1}" \
    BACKEND_HOST=0.0.0.0 \
    PORT="$BACKEND_PORT" \
    BACKEND_RELATIONAL_ENABLED="$RELATIONAL_ENABLED" \
    BACKEND_RELATIONAL_MODE="$RELATIONAL_MODE" \
    BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED="$RELATIONAL_SHADOW_SYNC_ENABLED" \
    BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE" \
    BACKEND_APP_STATE_SPLIT_TABLE_STATES="${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-off}" \
    BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" \
    BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD:-0}" \
    EVENT_OUTBOX_ENABLED="$EVENT_OUTBOX_FLAG" \
    PRINTING_ENABLED="${PRINTING_ENABLED:-1}" \
    PRINT_SPOOL_FAST_WORKER="${PRINT_SPOOL_FAST_WORKER:-1}" \
    PRINT_TCP_TIMEOUT_MS="${PRINT_TCP_TIMEOUT_MS:-2500}" \
    AUTO_PRINT_ENQUEUE_DELAY_MS="${AUTO_PRINT_ENQUEUE_DELAY_MS:-0}" \
    BACKEND_DB_MODE="${BACKEND_DB_MODE:-mysql}" \
    BACKEND_MYSQL_HOST="${BACKEND_MYSQL_HOST:-}" \
    BACKEND_MYSQL_PORT="${BACKEND_MYSQL_PORT:-}" \
    BACKEND_MYSQL_USER="${BACKEND_MYSQL_USER:-}" \
    BACKEND_MYSQL_PASSWORD="${BACKEND_MYSQL_PASSWORD:-}" \
    BACKEND_MYSQL_DATABASE="${BACKEND_MYSQL_DATABASE:-}" \
    BACKEND_MYSQL_SPLIT_SESSIONS=1 \
    BACKEND_MYSQL_SESSIONS_TABLE=app_state_sessions \
    BACKEND_MYSQL_SPLIT_AUDIT_EVENTS=1 \
    BACKEND_MYSQL_AUDIT_EVENTS_TABLE=app_state_audit_events \
    BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS="$MYSQL_APP_STATE_DOMAINS_FLAG" \
    BACKEND_MYSQL_APP_STATE_DOMAINS_TABLE=app_state_domain_records \
    BACKEND_MYSQL_TABLE_LOCKS=1 \
    BACKEND_ALLOW_EMPTY_DB_INIT="${BACKEND_ALLOW_EMPTY_DB_INIT:-1}" \
    BACKEND_ALLOW_MYSQL_IMPORT_JSON="${BACKEND_ALLOW_MYSQL_IMPORT_JSON:-1}" \
    BACKEND_DB_IMPORT_JSON_PATH="${BACKEND_DB_IMPORT_JSON_PATH-$APP_ROOT/cassa-frontend/backend/app-state.json}" \
    POS_FISCAL_API_BASE_URL="${POS_FISCAL_API_BASE_URL:-http://192.168.1.200:8765}" \
    BATTERY_SERVICE_URL="${BATTERY_SERVICE_URL:-http://127.0.0.1:8765/battery}" \
    BATTERY_SERVICE_TIMEOUT_MS=2500 \
    BATTERY_PROXY_CACHE_MS=750 \
    AUTOMATIC_CASH_GATEWAY_ENABLED="${AUTOMATIC_CASH_GATEWAY_ENABLED:-1}" \
    AUTOMATIC_CASH_GATEWAY_BASE_URL="${AUTOMATIC_CASH_GATEWAY_BASE_URL:-}" \
    AUTOMATIC_CASH_GATEWAY_USERNAME="${AUTOMATIC_CASH_GATEWAY_USERNAME:-}" \
    AUTOMATIC_CASH_GATEWAY_PASSWORD="${AUTOMATIC_CASH_GATEWAY_PASSWORD:-}" \
    AUTOMATIC_CASH_GATEWAY_TIMEOUT_MS="${AUTOMATIC_CASH_GATEWAY_TIMEOUT_MS:-120000}" \
    "$NODE_BIN" backend/server.js </dev/null >>"$BACKEND_OUT" 2>>"$BACKEND_ERR" &
  echo $! >"$BACKEND_PID"
)

wait_http "http://127.0.0.1:${BACKEND_PORT}/api/health" "Backend"

if [[ "$REALTIME_GATEWAY_ENABLED" == "1" ]]; then
  (
    cd "$APP_ROOT/cassa-frontend"
    nohup setsid env \
      NODE_ENV=development \
      BACKEND_PROCESS_ROLE=realtime-gateway \
      APP_STATE_DIRTY_TRACKING="${APP_STATE_DIRTY_TRACKING:-1}" \
      SCOPED_READS="${SCOPED_READS:-1}" \
      SSE_EVENT_PAYLOAD="${SSE_EVENT_PAYLOAD:-1}" \
      RUNTIME_METRICS="${RUNTIME_METRICS:-1}" \
      BACKEND_HOST=0.0.0.0 \
      PORT="$REALTIME_PORT" \
      BACKEND_RELATIONAL_ENABLED="$RELATIONAL_ENABLED" \
      BACKEND_RELATIONAL_MODE="$RELATIONAL_MODE" \
      BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED="$RELATIONAL_SHADOW_SYNC_ENABLED" \
      BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE" \
      BACKEND_APP_STATE_SPLIT_TABLE_STATES="${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-off}" \
      BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" \
      BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD:-0}" \
      EVENT_OUTBOX_ENABLED="$EVENT_OUTBOX_FLAG" \
      PRINTING_ENABLED=0 \
      BACKEND_DB_MODE="${BACKEND_DB_MODE:-mysql}" \
      BACKEND_MYSQL_HOST="${BACKEND_MYSQL_HOST:-}" \
      BACKEND_MYSQL_PORT="${BACKEND_MYSQL_PORT:-}" \
      BACKEND_MYSQL_USER="${BACKEND_MYSQL_USER:-}" \
      BACKEND_MYSQL_PASSWORD="${BACKEND_MYSQL_PASSWORD:-}" \
      BACKEND_MYSQL_DATABASE="${BACKEND_MYSQL_DATABASE:-}" \
      BACKEND_MYSQL_SPLIT_SESSIONS=1 \
      BACKEND_MYSQL_SESSIONS_TABLE=app_state_sessions \
      BACKEND_MYSQL_SPLIT_AUDIT_EVENTS=1 \
      BACKEND_MYSQL_AUDIT_EVENTS_TABLE=app_state_audit_events \
      BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS="$MYSQL_APP_STATE_DOMAINS_FLAG" \
      BACKEND_MYSQL_APP_STATE_DOMAINS_TABLE=app_state_domain_records \
      BACKEND_MYSQL_TABLE_LOCKS=1 \
      BACKEND_ALLOW_EMPTY_DB_INIT="${BACKEND_ALLOW_EMPTY_DB_INIT:-1}" \
      BACKEND_ALLOW_MYSQL_IMPORT_JSON="${BACKEND_ALLOW_MYSQL_IMPORT_JSON:-1}" \
      BACKEND_DB_IMPORT_JSON_PATH="${BACKEND_DB_IMPORT_JSON_PATH-$APP_ROOT/cassa-frontend/backend/app-state.json}" \
      POS_FISCAL_API_BASE_URL="${POS_FISCAL_API_BASE_URL:-http://192.168.1.200:8765}" \
      BATTERY_SERVICE_URL="${BATTERY_SERVICE_URL:-http://127.0.0.1:8765/battery}" \
      "$NODE_BIN" backend/server.js </dev/null >>"$REALTIME_OUT" 2>>"$REALTIME_ERR" &
    echo $! >"$REALTIME_PID"
  )
  wait_http "http://127.0.0.1:${REALTIME_PORT}/api/health" "Realtime backend"
fi

if [[ "$API_WORKER_ENABLED" == "1" ]]; then
  rm -f "$API_WORKER_PID"
  first_api_worker_pid_written=0
  for worker_port in "${API_WORKER_PORT_LIST[@]}"; do
    worker_pid_file="$LOG_DIR/backend-api-worker-${worker_port}.pid"
    worker_out="$LOG_DIR/backend-api-worker-${worker_port}.out.log"
    worker_err="$LOG_DIR/backend-api-worker-${worker_port}.err.log"
  (
    cd "$APP_ROOT/cassa-frontend"
    nohup setsid env \
      NODE_ENV=development \
      BACKEND_PROCESS_ROLE=api-worker \
      APP_STATE_DIRTY_TRACKING="${APP_STATE_DIRTY_TRACKING:-1}" \
      SCOPED_READS="${SCOPED_READS:-1}" \
      SSE_EVENT_PAYLOAD="${SSE_EVENT_PAYLOAD:-1}" \
      RUNTIME_METRICS="${RUNTIME_METRICS:-1}" \
      BACKEND_HOST=0.0.0.0 \
      PORT="$worker_port" \
      BACKEND_PORT="$worker_port" \
      BACKEND_RELATIONAL_ENABLED="$RELATIONAL_ENABLED" \
      BACKEND_RELATIONAL_MODE="$RELATIONAL_MODE" \
      BACKEND_RELATIONAL_SHADOW_SYNC_ENABLED="$RELATIONAL_SHADOW_SYNC_ENABLED" \
      BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE" \
      BACKEND_APP_STATE_SPLIT_TABLE_STATES="${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-off}" \
      BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" \
      BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD:-0}" \
      EVENT_OUTBOX_ENABLED="$EVENT_OUTBOX_FLAG" \
      PRINTING_ENABLED=0 \
      BACKEND_DB_MODE="${BACKEND_DB_MODE:-mysql}" \
      BACKEND_MYSQL_HOST="${BACKEND_MYSQL_HOST:-}" \
      BACKEND_MYSQL_PORT="${BACKEND_MYSQL_PORT:-}" \
      BACKEND_MYSQL_USER="${BACKEND_MYSQL_USER:-}" \
      BACKEND_MYSQL_PASSWORD="${BACKEND_MYSQL_PASSWORD:-}" \
      BACKEND_MYSQL_DATABASE="${BACKEND_MYSQL_DATABASE:-}" \
      BACKEND_MYSQL_SPLIT_SESSIONS=1 \
      BACKEND_MYSQL_SESSIONS_TABLE=app_state_sessions \
      BACKEND_MYSQL_SPLIT_AUDIT_EVENTS=1 \
      BACKEND_MYSQL_AUDIT_EVENTS_TABLE=app_state_audit_events \
      BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS="$MYSQL_APP_STATE_DOMAINS_FLAG" \
      BACKEND_MYSQL_APP_STATE_DOMAINS_TABLE=app_state_domain_records \
      BACKEND_MYSQL_TABLE_LOCKS=1 \
      BACKEND_ALLOW_EMPTY_DB_INIT="${BACKEND_ALLOW_EMPTY_DB_INIT:-1}" \
      BACKEND_ALLOW_MYSQL_IMPORT_JSON="${BACKEND_ALLOW_MYSQL_IMPORT_JSON:-1}" \
      BACKEND_DB_IMPORT_JSON_PATH="${BACKEND_DB_IMPORT_JSON_PATH-$APP_ROOT/cassa-frontend/backend/app-state.json}" \
      POS_FISCAL_API_BASE_URL="${POS_FISCAL_API_BASE_URL:-http://192.168.1.200:8765}" \
      BATTERY_SERVICE_URL="${BATTERY_SERVICE_URL:-http://127.0.0.1:8765/battery}" \
      "$NODE_BIN" backend/server.js </dev/null >>"$worker_out" 2>>"$worker_err" &
    echo $! >"$worker_pid_file"
  )
    if [[ "$first_api_worker_pid_written" == "0" ]]; then
      cp "$worker_pid_file" "$API_WORKER_PID"
      first_api_worker_pid_written=1
    fi
    wait_http "http://127.0.0.1:${worker_port}/api/health" "API worker backend ${worker_port}"
  done
fi

(
  cd "$APP_ROOT"
  nohup setsid env \
    FRONTEND_HOST=0.0.0.0 \
    FRONTEND_PORT="$FRONTEND_PORT" \
    BACKEND_ORIGIN="http://127.0.0.1:${BACKEND_PORT}" \
    BACKEND_REALTIME_ORIGIN="$FRONTEND_REALTIME_ORIGIN" \
    BACKEND_API_WORKER_ORIGIN="$FRONTEND_API_WORKER_ORIGIN" \
    BACKEND_MULTI_PROCESS_ORDER_WORKFLOW_AUDIT_GO="$ORDER_WORKFLOW_AUDIT_GO_EFFECTIVE" \
    BACKEND_APP_STATE_SPLIT_TABLE_STATES="${BACKEND_APP_STATE_SPLIT_TABLE_STATES:-off}" \
    BACKEND_MYSQL_SPLIT_APP_STATE_DOMAINS="$MYSQL_APP_STATE_DOMAINS_FLAG" \
    BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ROUTE_ALLOWLIST:-}" \
    BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD="${BACKEND_MULTI_PROCESS_ORDER_WORKER_ALLOW_WILDCARD:-0}" \
    FRONTEND_ROOT="$APP_ROOT" \
    FRONTEND_HTTPS=true \
    FRONTEND_LAN_IP="$LAN_IP" \
    FRONTEND_HTTPS_CERT="$CERT_PATH" \
    FRONTEND_HTTPS_KEY="$KEY_PATH" \
    "$NODE_BIN" serve-frontends.mjs </dev/null >>"$FRONTEND_OUT" 2>>"$FRONTEND_ERR" &
  echo $! >"$FRONTEND_PID"
)

wait_http "https://127.0.0.1:${FRONTEND_PORT}/mobile/" "Frontend HTTPS"

echo "Backend PID: $(cat "$BACKEND_PID")"
if [[ "$REALTIME_GATEWAY_ENABLED" == "1" ]]; then
  echo "Realtime backend PID: $(cat "$REALTIME_PID")"
  echo "Realtime backend origin: $FRONTEND_REALTIME_ORIGIN"
fi
if [[ "$API_WORKER_ENABLED" == "1" ]]; then
  for worker_port in "${API_WORKER_PORT_LIST[@]}"; do
    worker_pid_file="$LOG_DIR/backend-api-worker-${worker_port}.pid"
    echo "API worker backend ${worker_port} PID: $(cat "$worker_pid_file")"
  done
  echo "API worker backend origins: $FRONTEND_API_WORKER_ORIGIN"
fi
echo "Frontend PID: $(cat "$FRONTEND_PID")"
echo "Frontend LAN URL: https://${LAN_IP}:${FRONTEND_PORT}/mobile/"
