export function buildReportsRoutes() {
  return [
    {
      method: "POST",
      path: "/api/audit/events",
      handlerKey: "audit.events",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Consultazione audit con filtri senza scrittura DB.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/audit/events/delete",
      handlerKey: "audit.eventDelete",
      mutation: true,
      authRequired: true,
      permission: "manage_users",
    },
    {
      method: "POST",
      path: "/api/reports/sales",
      handlerKey: "reports.sales",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Calcolo report vendite dalla snapshot DB senza scrittura.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/reports/handheld-session",
      handlerKey: "reports.handheldSession",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Riepilogo sessioni palmari senza apertura, chiusura o stampa.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/reports/handheld-session/cash/open",
      handlerKey: "reports.handheldCashSessionOpen",
      mutation: true,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/reports/handheld-session/cash/close",
      handlerKey: "reports.handheldCashSessionClose",
      mutation: true,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/reports/handheld-session/print",
      handlerKey: "reports.handheldSessionPrint",
      mutation: true,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/reports/non-fiscalized",
      handlerKey: "reports.nonFiscalized",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Report scontrini non fiscalizzati senza retry o stampa.",
      authRequired: true,
    },
  ];
}
