export function buildSettingsRoutes() {
  return [
    {
      method: "POST",
      path: "/api/settings/configuration/snapshot",
      handlerKey: "settings.configurationSnapshot",
      mutation: false,
      readOnly: true,
      readOnlyReason:
        "Lettura snapshot configurazione locale-attivita-sale per frontend impostazioni.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/settings/pos",
      handlerKey: "settings.pos",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Lettura impostazioni POS senza scrittura DB.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/settings/pos/areas",
      handlerKey: "settings.posAreas",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Lettura aree POS senza scrittura DB.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/settings/pos/areas/save",
      handlerKey: "settings.savePosAreas",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
    {
      method: "POST",
      path: "/api/settings/pos/print-preferences/save",
      handlerKey: "settings.savePrintPreferences",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
    {
      method: "POST",
      path: "/api/settings/pos/general/save",
      handlerKey: "settings.saveGeneral",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
    {
      method: "POST",
      path: "/api/settings/pos/payment-methods",
      handlerKey: "settings.savePaymentMethods",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
    {
      method: "POST",
      path: "/api/settings/user/payment-preferences",
      handlerKey: "settings.userPaymentPreferences",
      mutation: false,
      readOnly: true,
      readOnlyReason: "Lettura preferenze pagamenti dell'utente corrente.",
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/settings/user/payment-preferences/save",
      handlerKey: "settings.saveUserPaymentPreferences",
      mutation: true,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/settings/mobile-devices/save",
      handlerKey: "settings.saveMobileDevices",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
    {
      method: "POST",
      path: "/api/settings/mobile-devices/ring",
      handlerKey: "settings.ringMobileDevice",
      mutation: true,
      authRequired: true,
      permission: "manage_settings",
    },
  ];
}
