export function buildAutomaticCashRoutes() {
  return [
    {
      method: "GET",
      path: "/api/automatic-cash/settings",
      handlerKey: "automaticCash.settings",
      mutation: false,
      authRequired: true,
    },
    {
      method: "PUT",
      path: "/api/automatic-cash/settings",
      handlerKey: "automaticCash.saveSettings",
      mutation: true,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/config-sets",
      handlerKey: "automaticCash.uploadConfigSet",
      mutation: true,
      authRequired: true,
      maxBodySize: 524_288,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/config-sets/default-100",
      handlerKey: "automaticCash.uploadDefaultConfigSet",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/reserve-configs",
      handlerKey: "automaticCash.uploadReserveConfig",
      mutation: true,
      authRequired: true,
      maxBodySize: 524_288,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/status",
      handlerKey: "automaticCash.status",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/gateway/state",
      handlerKey: "automaticCash.gatewayState",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/gateway/restart",
      handlerKey: "automaticCash.gatewayRestart",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/gateway/reset",
      handlerKey: "automaticCash.gatewayReset",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-movements",
      handlerKey: "automaticCash.cashMovements",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-movements/active",
      handlerKey: "automaticCash.activeCashMovement",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-movements/withdrawal-availability",
      handlerKey: "automaticCash.cashMovementWithdrawalAvailability",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-movements/:movementId/state",
      handlerKey: "automaticCash.cashMovementState",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-movements/start",
      handlerKey: "automaticCash.startCashMovement",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-movements/:movementId/prepare",
      handlerKey: "automaticCash.prepareCashMovement",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-movements/:movementId/complete",
      handlerKey: "automaticCash.completeCashMovement",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-movements/:movementId/print",
      handlerKey: "automaticCash.printCashMovementReport",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-movements/:movementId/cancel",
      handlerKey: "automaticCash.cancelCashMovement",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-float/preflight",
      handlerKey: "automaticCash.cashFloatPreflight",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/cash-float/active",
      handlerKey: "automaticCash.activeCashFloatWorkflow",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-float/generate",
      handlerKey: "automaticCash.generateCashFloat",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-float/confirm-removed",
      handlerKey: "automaticCash.confirmCashFloatRemoved",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-float/ticket/printed",
      handlerKey: "automaticCash.cashFloatTicketPrinted",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-float/confirm-ticket-in-pouch",
      handlerKey: "automaticCash.confirmCashFloatTicketInPouch",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/cash-float/load-from-qr",
      handlerKey: "automaticCash.loadCashFloatFromQr",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/settlements",
      handlerKey: "automaticCash.listSettlementRecords",
      mutation: false,
      authRequired: true,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/settlements/latest",
      handlerKey: "automaticCash.latestSettlementRecord",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/settlements",
      handlerKey: "automaticCash.saveSettlementRecord",
      mutation: true,
      authRequired: true,
      maxBodySize: 98_304,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/deposit/start",
      handlerKey: "automaticCash.startDeposit",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/deposit/close",
      handlerKey: "automaticCash.closeDeposit",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/deposit/cancel",
      handlerKey: "automaticCash.cancelDeposit",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/exchange/active",
      handlerKey: "automaticCash.activeCashExchange",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/payment/start",
      handlerKey: "automaticCash.startCashPayment",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/payment/:operationId/state",
      handlerKey: "automaticCash.cashPaymentState",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/payment/:operationId/complete",
      handlerKey: "automaticCash.completeCashPayment",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/payment/:operationId/cancel",
      handlerKey: "automaticCash.cancelCashPayment",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/exchange/start",
      handlerKey: "automaticCash.startCashExchange",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "GET",
      path: "/api/automatic-cash/exchange/:exchangeId/state",
      handlerKey: "automaticCash.cashExchangeState",
      mutation: false,
      authRequired: true,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/exchange/:exchangeId/cancel",
      handlerKey: "automaticCash.cancelCashExchange",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/exchange/:exchangeId/confirm-deposit",
      handlerKey: "automaticCash.confirmCashExchangeDeposit",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/exchange/:exchangeId/execute",
      handlerKey: "automaticCash.executeCashExchange",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
    {
      method: "POST",
      path: "/api/automatic-cash/exchange/:exchangeId/confirm-removed",
      handlerKey: "automaticCash.confirmCashExchangeRemoved",
      mutation: true,
      authRequired: true,
      maxBodySize: 65_536,
    },
  ];
}
