export function buildAppStateRoutes() {
  return [
    {
      method: "GET",
      path: "/api/app-state",
      handlerKey: "appState.get",
      mutation: false,
      authRequired: true,
      admin: true,
    },
    {
      method: "POST",
      path: "/api/app-state/sync",
      handlerKey: "appState.sync",
      mutation: true,
      authRequired: true,
      admin: true,
    },
    {
      method: "POST",
      path: "/api/maintenance/app-state/reset",
      handlerKey: "appState.reset",
      mutation: true,
      authRequired: true,
      debug: true,
      permission: "manage_users",
    },
    {
      method: "POST",
      path: "/api/app-state/reset",
      handlerKey: "appState.reset",
      mutation: true,
      authRequired: true,
      debug: true,
      permission: "manage_users",
      legacy: true,
      note: "Alias legacy temporaneo; richiede endpoint debug abilitati.",
    },
    {
      method: "GET",
      path: "/api/mock-db",
      handlerKey: "appState.get",
      mutation: false,
      authRequired: true,
      debug: true,
      permission: "manage_users",
      legacy: true,
      note: "Alias legacy read-only di /api/app-state.",
    },
    {
      method: "POST",
      path: "/api/mock-db/reset",
      handlerKey: "appState.reset",
      mutation: true,
      authRequired: true,
      debug: true,
      permission: "manage_users",
      legacy: true,
      note: "Alias legacy reset; da rimuovere dopo aggiornamento client/script esterni.",
    },
  ];
}
