export function buildStatusRoutes() {
  return [
    {
      method: "GET",
      path: "/api/health",
      handlerKey: "health",
      mutation: false,
      public: true,
      authRequired: false,
    },
    {
      method: "GET",
      path: "/api/settings/order-workflow",
      handlerKey: "settings.orderWorkflow",
      mutation: false,
      public: true,
      authRequired: false,
    },
    {
      method: "GET",
      path: "/api/settings/payment-methods",
      handlerKey: "settings.paymentMethods",
      mutation: false,
      public: true,
      authRequired: false,
    },
    {
      method: "GET",
      path: "/api/settings/payment-terminals",
      handlerKey: "settings.paymentTerminals",
      mutation: false,
      public: true,
      authRequired: false,
    },
    {
      method: "GET",
      path: "/api/monitor/overview",
      handlerKey: "monitor.overview",
      mutation: false,
      public: true,
      authRequired: false,
    },
    {
      method: "GET",
      path: "/api/monitor/runtime-metrics",
      handlerKey: "monitor.runtimeMetrics",
      mutation: false,
      authRequired: true,
      admin: true,
    },
    {
      method: "GET",
      path: "/api/internal/monitor/runtime-metrics",
      handlerKey: "monitor.runtimeMetricsInternal",
      mutation: false,
      authRequired: true,
      service: "integration",
    },
    {
      method: "POST",
      path: "/api/monitor/runtime-metrics/reset",
      handlerKey: "monitor.runtimeMetricsReset",
      mutation: true,
      authRequired: true,
      admin: true,
    },
    {
      method: "POST",
      path: "/api/monitor/control",
      handlerKey: "monitor.control",
      mutation: true,
      authRequired: true,
      admin: true,
    },
  ];
}
